enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  WELLCOME_SCREEN ='WELLCOME_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_METHOD ='SIGNUP_METHOD',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORD_RESET = 'PASSWORD_RESET',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  ASK_NAME ='ASK_NAME',
  ASK_AGE ='ASK_AGE',
  ASK_LIVE ='ASK_LIVE',
  ASK_SELF='ASK_SELF',
  ASK_RELATIONSHIP ='ASK_RELATIONSHIP',
  ASK_LOOKING='ASK_LOOKING',
  ASK_ABOUT ='ASK_ABOUT',
  ASK_FINAL ='ASK_FINAL',
  CHAT_SCREEN='CHAT_SCREEN',

  BOTTOM_TAB = 'BOTTOM_TAB',

  BIOGRAPHY = 'BIOGRAPHY',
  CHANGE_IDENTIFIER = 'CHANGE_IDENTIFIER',
  DISTANCE = 'DISTANCE',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  CONTACT_US = 'CONTACT_US',
  GENERAL_CONDITIONS = 'GENERAL_CONDITIONS',
  CONDITIONS_OF_USE = 'CONDITIONS_OF_USE',
  SETTINGS = 'SETTINGS',
  SUBSCRIPTION = 'SUBSCRIPTION',
  Chat_Contact='Chat_Contact',
  Findmatches='Findmatches',
  Message ='Message',
  ChangePassword='ChangePassword',
  Ratting='Ratting'
}

export default ScreenNameEnum;
