const hobbies = [
    { id: '1', value: 'Reading' },
    { id: '2', value: 'Traveling' },
    { id: '3', value: 'Cooking' },
    { id: '4', value: 'Hiking' },
    { id: '5', value: 'Photography' },
    { id: '6', value: 'Playing Sports' },
    { id: '7', value: 'Watching Movies' },
    { id: '8', value: 'Gardening' },
    { id: '9', value: 'Painting' },
    { id: '10', value: 'Yoga' },
    { id: '11', value: 'Dancing' },
    { id: '12', value: 'Writing' },
    { id: '13', value: 'Playing Musical Instruments' },
    { id: '14', value: 'Gaming' },
    { id: '15', value: 'Swimming' },
    { id: '16', value: 'Fishing' },
    { id: '17', value: 'Crafting' },
    { id: '18', value: 'Biking' },
    { id: '19', value: 'Running' },
    { id: '20', value: 'Bird Watching' },
    { id: '21', value: 'Surfing' },
    { id: '22', value: 'Volunteering' },
    { id: '23', value: 'Knitting' },
    { id: '24', value: 'Rock Climbing' },
    { id: '25', value: 'Meditating' },
    { id: '26', value: 'Collecting (stamps, coins, etc.)' },
    { id: '27', value: 'Attending Concerts' },
    { id: '28', value: 'Wine Tasting' },
    { id: '29', value: 'Learning Languages' },
    { id: '30', value: 'Astronomy' },
  ];